name: 24/7 Monitor & Redeploy

on:
  schedule:
    - cron: '*/1 * * * *'  # Every minute

jobs:
  ensure-availability:
    runs-on: ubuntu-latest
    steps:
      - name: Keep Alive & Health Check
        id: health-check
        run: |
          echo "[$(date)] Starting keep-alive loop..."

          # Send repeated requests to keep the service awake
          for i in {1..10}; do
            curl -s https://cb-auto.onrender.com/healthz  > /dev/null
            echo "[$(date)] Ping $i completed."
            sleep 10
          done

          # Final health check
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" https://cb-auto.onrender.com/healthz )
          echo "[$(date)] Final HTTP status: \$RESPONSE"

          if [ "$RESPONSE" -ne 200 ]; then
            echo "status=unhealthy" >> $GITHUB_OUTPUT
          else
            echo "status=healthy" >> $GITHUB_OUTPUT
          fi

      - name: Redeploy if Unhealthy
        if: steps.health-check.outputs.status == 'unhealthy'
        run: |
          echo "[$(date)] Service is unhealthy. Triggering redeploy..."
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Content-Type: application/json" \
            "https://api.render.com/v1/services/web/${{ secrets.RENDER_SERVICE_ID }}/deploys"

      - name: Notify Telegram
        if: always()
        run: |
          STATUS="${{ job.status }}"
          TIMESTAMP=$(date)
          MESSAGE="🔄 *CB-Auto Deployment Status*\n\n⏱ Scheduled Job Run: $TIMESTAMP\n🚦 Status: $STATUS"

          curl -s -X POST \
            "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d "chat_id=${{ secrets.AUTHORIZED_USERS }}" \
            -d "text=$MESSAGE" \
            -d "parse_mode=Markdown"

